# models/sources.yml
version: 2

sources:
  - name: raw
    description: "Raw data loaded from external sources"
    tables:

      - name: wfo_taxonomy
        description: "World Flora Online taxonomy data"
        
      - name: gbif_taxonomy  
        description: "GBIF Backbone Taxonomy data"

      - name: wiz_species
        description: "OrchidWiz species data"
        
      - name: wiz_genera
        description: "OrchidWiz genera classification data"
        
      - name: wiz_classifications
        description: "OrchidWiz genera classification data"

      - name: wiz_infras
        description: "Infraspecific varieties, forms, and subspecies of orchids"
        
      - name: wiz_species_names
        description: "More data about species"

        